name: Test Jest CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci,
      - name: Install Jest
        run: npm install jest --global
      - name: Run Jest Watch
        run: npm run test --ci
